package com.qpgs.backend.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.LineSeparator;
import com.qpgs.backend.entity.GeneratedPaper;
import com.qpgs.backend.entity.Question;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ExportService {

    @Autowired
    private PaperGenerationService paperGenerationService;

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

    public byte[] exportToPdf(Long paperId) {
        GeneratedPaper paper = paperGenerationService.getPaperById(paperId);

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Font metaFont = new Font(Font.FontFamily.HELVETICA, 11, Font.NORMAL);
            Font questionFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
            Font marksFont = new Font(Font.FontFamily.HELVETICA, 11, Font.ITALIC);

            Paragraph title = new Paragraph(paper.getSubject() + " - Question Paper", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            Paragraph meta = new Paragraph();
            meta.setFont(metaFont);
            meta.add("Generated By: " + paper.getGeneratedBy() + "\n");
            meta.add("Date: " + paper.getGeneratedDate().format(DATE_FORMAT) + "\n");
            meta.add("Total Questions: " + paper.getTotalQuestions() + "\n");
            meta.add("Total Marks: " + paper.getTotalMarks());
            document.add(meta);
            document.add(Chunk.NEWLINE);

            document.add(new LineSeparator());
            document.add(Chunk.NEWLINE);

            List<Question> questions = paper.getQuestions();
            int qNo = 1;
            for (Question q : questions) {
                Paragraph qPara = new Paragraph();
                qPara.setSpacingAfter(12);
                qPara.add(new Chunk(qNo + ". ", questionFont));
                qPara.add(new Chunk(q.getQuestionText() + "  ", questionFont));
                qPara.add(new Chunk("[" + q.getMarks() + " marks]", marksFont));
                document.add(qPara);
                qNo++;
            }

            document.close();
            return out.toByteArray();

        } catch (DocumentException e) {
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    public byte[] exportToWord(Long paperId) {
        GeneratedPaper paper = paperGenerationService.getPaperById(paperId);

        try (XWPFDocument document = new XWPFDocument();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            XWPFParagraph titlePara = document.createParagraph();
            titlePara.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun titleRun = titlePara.createRun();
            titleRun.setText(paper.getSubject() + " - Question Paper");
            titleRun.setBold(true);
            titleRun.setFontSize(18);

            XWPFParagraph metaPara = document.createParagraph();
            XWPFRun metaRun = metaPara.createRun();
            metaRun.setFontSize(11);
            metaRun.setText("Generated By: " + paper.getGeneratedBy());
            metaRun.addBreak();
            metaRun.setText("Date: " + paper.getGeneratedDate().format(DATE_FORMAT));
            metaRun.addBreak();
            metaRun.setText("Total Questions: " + paper.getTotalQuestions());
            metaRun.addBreak();
            metaRun.setText("Total Marks: " + paper.getTotalMarks());

            document.createParagraph(); // spacer

            List<Question> questions = paper.getQuestions();
            int qNo = 1;
            for (Question q : questions) {
                XWPFParagraph qPara = document.createParagraph();
                qPara.setSpacingAfter(150);
                XWPFRun qRun = qPara.createRun();
                qRun.setFontSize(12);
                qRun.setText(qNo + ". " + q.getQuestionText() + "  [" + q.getMarks() + " marks]");
                qNo++;
            }

            document.write(out);
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate Word document: " + e.getMessage(), e);
        }
    }
}